### PR TITLE
Change hempcrete recipe from fern to wheat to actually be automatable

### PR DESCRIPTION
**Pull request by S4mpsa**
Changes the recipe from 8 Sand + 1 Fern to 8 Sand + 1 Wheat, thematically the same but Fern is basically impossible to automate.

### CODE REVIEW

**Comment by chochem** [comment]
you can automate fern with botania

**Review by boubou19 — APPROVED** [review]

**Comment by boubou19** [comment]
why does this have to be insanely tedious for people who don't even know botania automation? And it's for cosmetic blocks. The fact cosmetic blocks are insanely pricey / tedious to the point people reject the option even if it becomes quickly trivial to mass craft around HV is a great indicator that it's dumb.

**Comment by Dream-Master** [comment]
i think the recipe change it ok.

**Comment by Dream-Master** [comment]
maybe we can rename the block

**Comment by chochem** [comment]
change the quest too if you do

**Comment by Alastors** [comment]
Call it biocrete

**Pull request merged**
